#+TITLE:       Vis-Karma: Visualization of Karma Relationships
#+AUTHOR:      Yali Bian
#+EMAIL:       byl.lisp@gmail.com
#+DATE:        2015-08-25 Tue


Vis-Karma is a visualization system to represent the relations of causes and effects of karma in Buddhism.
The main view is based on [[https://github.com/mbostock/d3/wiki/Bundle-Layout][Bundle Layout]] in [[http://d3js.org/][D3.js]] which implements Danny Holten's [[http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.220.8113&rep=rep1&type=pdf][hierarchical edge bundling algorithm]].

* Demo

  There are two demos of this system, the [[http://www.lisp.one/vis/karma][one with a backend]] and [[http://karma.lisp.one][one without backend]].
  The first one can store the changes of the input, output nodes, and their relationships on the bakend database.
  The second one, on the other hand, is used for expression for everyone, so no one can change the basic informations that the system has, though you can change it instantly.

* Usage

  The demo is as follows: The left side nodes are input "causes", the right sides nodes are output "effects", just like general functions:
  file:./org/demo-1.png

  When click the text, you can modify the information of the input or output nodes.

  When move the mouse on words such as "邪见", links between the node "邪见" and effects nodes emerge, which show the cause and it's effects, and more information will appear at the info-box in left or right side.

  You can drag one input node to a output node, to add, delete or modify the relationship between the input "cause" and output "effect".

* Build

  If you want to build this system on your own pc, you should:
  + Download [[www.racket-lang.org][DrRacket]] from racket-lang
  + Install DrRacket
  + Download this repo
  + open file "run.rkt" in this repo using GrRacket
  + Click "Run" on Top Right of GrRacket
  + Open "http://localhost:9999" in your Browser (Like Chrome, Firfox, or Safari).


* License

  MIT license (© 2015 Yali Bian)
